# Generated by Django 3.2 on 2021-04-09 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0004_lists_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='deadline',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='items',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
