# Generated by Django 3.2 on 2021-04-09 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0005_auto_20210409_2148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='slug',
        ),
    ]
