# Generated by Django 3.2 on 2021-04-08 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_userprofile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='country',
        ),
    ]
